sudo: required
language: rust
branches:
  only:
  - master
  - dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

services:
  - docker

before_install:
  - ./scripts/setup_test_env.sh

script:
  - cargo build
  - mkdir tokens
  - cargo run -- --token-dir ./tokens --pepper=PEPPER --db "postgres://synapse:synapse@localhost:5433/synapse" &
  - sleep 1
  - cargo test --features=integ-tests
