[package]
name = "synapse-password-reset"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]

[dependencies]
nickel = "*"
nickel_mustache = { git = "https://github.com/euank/nickel-mustache" }

rustc-serialize = "*"
