#!/usr/bin/env bash

# Synapse password reset
# Copyright (C) 2016 Euan Kemp
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SOURCE=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )

set -e
set -x
set -o nounset
set -o pipefail

short_hash=$(git rev-parse --short HEAD)

if [[ ! -x "${SOURCE}/../target/release/synapse-password-reset" ]]; then
  echo "no release build handy"
  exit 1
fi

docker build -t euank/synapse-password-reset:latest -f "${SOURCE}/Dockerfile.release" "${SOURCE}/.."

docker tag euank/synapse-password-reset:latest euank/synapse-password-reset:${short_hash}

docker push euank/synapse-password-reset:latest
docker push euank/synapse-password-reset:${short_hash}
