FROM debian:jessie

RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt

RUN mkdir -p /app/tokens
RUN useradd -d /app app
WORKDIR /app

COPY ./target/release/synapse-password-reset /app/synapse-password-reset
RUN chown app:app /app/tokens /app

USER app

ENTRYPOINT ["/app/synapse-password-reset"]
