FROM rust:1.89.0

RUN apt-get update && apt-get install -y libssl-dev

COPY ./Cargo.lock ./Cargo.toml ./LICENSE /rust/app/
COPY ./src /rust/app/src

WORKDIR /rust/app

CMD ["cargo", "build", "--release"]
